version: "3"

networks:
  bitcoin:

volumes:
  data:

services:
  bcoin_app:
    container_name: bcoin_app
    image: bcoin_app_${BCOIN_NETWORK}
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
      - 35729:35729
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
      NODE_ENV: development
      PORT: ${REACT_APP_PORT}
      CHOKIDAR_USEPOLLING: "true" 
    depends_on:
      - bcoin_api
    links:
      - bcoin_api
    networks:
      - bitcoin

  bcoin_api:
    container_name: bcoin_api
    image: bcoin_api_${BCOIN_NETWORK}
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
      - 5858:5858
    volumes:
      - ./api/src:/usr/src/api/src
    environment:
      PORT: $API_PORT
      BCOIN_HOST: $BCOIN_HOST
      BCOIN_API_KEY: $BCOIN_API_KEY
      BCOIN_NETWORK: ${BCOIN_NETWORK}
      NODE_ENV: development
    depends_on:
      - bcoin_node
    networks:
      - bitcoin

  bcoin_node:
    container_name: bcoin_node
    image: bcoin_node_${BCOIN_NETWORK}
    hostname: localhost
    build:
      context: ./bcoin
      dockerfile: ./Dockerfile
    ports:
      - 48444:48444 # bcoin Node
      - 48332:48332 # RPC
      - 48334:48334 # Wallet
    logging:
      driver: none
    networks:
      - bitcoin
