version: "3"

networks:
  bitcoin:

volumes:
  data:

services:
  bcoin_app:
    container_name: bcoin_app
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    ports:
      - ${REACT_APP_PORT}:80
    volumes:
      - ./app:/app/app
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    depends_on:
      - bcoin_api
    links:
      - bcoin_api
    networks:
      - bitcoin

  bcoin_api:
    container_name: bcoin_api
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/app/api
    environment:
      PORT: ${API_PORT}
      BCOIN_API_KEY: ${BCOIN_API_KEY}
      BCOIN_NETWORK: ${BCOIN_NETWORK}
      BCOIN_HOST: ${BCOIN_HOST}
    depends_on:
      - bcoin_node
    networks:
      - bitcoin

  bcoin_node:
    container_name: bcoin_node
    hostname: localhost
    build:
      context: ./bcoin
      dockerfile: ../docker/node.Dockerfile
    ports:
      - 48444:48444 # bcoin Node
      - 48332:48332 # RPC
      - 48334:48334 # Wallet
    logging:
      driver: none
    networks:
      - bitcoin
